[workspace]
resolver = "2"
members = [
    "crates/pflow-core",
    "crates/pflow-solver",
    "crates/pflow-tokenmodel",
    "crates/pflow-dsl",
    "crates/pflow-macros",
    "crates/pflow-zk",
    "crates/pflow-zk-arkworks",
    "crates/pflow-zk-risc0",
    "crates/pflow",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/pflow-xyz/pflow-rs"
homepage = "https://pflow.xyz"
