//! Gradient-check for `solve_adjoint` (`adjoint.rs`), the reverse-mode counterpart of
//! forward-mode sensitivities.
//!
//! go-pflow is the sole reference for the adjoint: pflow-xyz's `petri-learn.js` never
//! wired it into its own `fit()`, so there is no cross-language golden fixture to check
//! against. Per the task's own instruction, these tests validate the adjoint gradient
//! two independent ways, mirroring go-pflow's own `learn/adjoint_test.go`
//! (`TestAdjointVsFDDecayMSE`, `TestAdjointVsFDSIRMSE`):
//!
//! (a) against forward mode's own gradient (`solve_with_sensitivities` +
//!     `mse_loss_grad` / `relative_mse_loss_grad`) on the same small net — two
//!     independently derived methods computing the same quantity must agree, and
//! (b) directly against a central finite difference of `MSELoss`/`RelativeMSELoss`
//!     itself, rebuilding the `LearnableProblem` at theta +/- h and re-solving from
//!     scratch (`adjoint_matches_direct_fd_*` below) — the same direct FD gate go-pflow
//!     runs, which (a) alone cannot provide: an error shared by both the adjoint and
//!     forward-mode derivations would pass (a) but not (b).

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use pflow_core::net::PetriNet;
use pflow_core::State;
use pflow_learn::{mse_loss, mse_loss_grad};
use pflow_learn::{
    mse_loss_adjoint, relative_mse_loss_adjoint, relative_mse_loss_grad, solve_with_sensitivities,
    Dataset, LearnError, LearnableProblem, ScalarRateFunc,
};
use pflow_solver::methods;
use pflow_solver::ode::Options;

/// A -> t1 -> B, single rate parameter (closed form A(t) = A0 * exp(-theta t)).
fn decay_problem(theta: f64) -> LearnableProblem {
    let net = PetriNet::build()
        .place("A", 10.0)
        .place("B", 0.0)
        .transition("t1")
        .arc("A", "t1", 1.0)
        .arc("t1", "B", 1.0)
        .done();
    let u0: State = [("A".to_string(), 10.0), ("B".to_string(), 0.0)]
        .into_iter()
        .collect();
    let mut prob = LearnableProblem::new(net, u0, [0.0, 2.0]);
    prob.set_rate_func("t1", Rc::new(RefCell::new(ScalarRateFunc::new(theta))));
    prob
}

/// A + B -> t1 -> C -> t2 -> D, two independent rate parameters and a bimolecular
/// (two-input) transition, exercising the prefix/suffix product-rule term the same way
/// `tests/finite_diff.rs` does for forward mode.
fn bimolecular_problem(theta1: f64, theta2: f64) -> LearnableProblem {
    let net = PetriNet::build()
        .place("A", 5.0)
        .place("B", 3.0)
        .place("C", 0.0)
        .place("D", 0.0)
        .transition("t1")
        .transition("t2")
        .arc("A", "t1", 1.0)
        .arc("B", "t1", 1.0)
        .arc("t1", "C", 1.0)
        .arc("C", "t2", 1.0)
        .arc("t2", "D", 1.0)
        .done();
    let u0: State = [
        ("A".to_string(), 5.0),
        ("B".to_string(), 3.0),
        ("C".to_string(), 0.0),
        ("D".to_string(), 0.0),
    ]
    .into_iter()
    .collect();
    let mut prob = LearnableProblem::new(net, u0, [0.0, 1.0]);
    prob.set_rate_func("t1", Rc::new(RefCell::new(ScalarRateFunc::new(theta1))));
    prob.set_rate_func("t2", Rc::new(RefCell::new(ScalarRateFunc::new(theta2))));
    prob
}

fn solve_opts() -> Options {
    Options {
        dt: 1e-3,
        dtmin: 1e-7,
        dtmax: 0.1,
        abstol: 1e-8,
        reltol: 1e-6,
        maxiters: 500_000,
        adaptive: true,
    }
}

fn assert_close(name: &str, a: f64, b: f64, atol: f64, rtol: f64) {
    let scale = atol + rtol * a.abs().max(b.abs());
    let diff = (a - b).abs();
    assert!(
        diff <= scale,
        "{name}: {a} vs {b} (|diff|={diff} > tol={scale})"
    );
}

/// Builds a dataset of `place -> observed values` at `times`, generated by solving
/// `gen_prob` and reading its trajectory back at those times — so the dataset is
/// internally consistent regardless of which problem it's later fit against.
fn dataset_from(gen_prob: &LearnableProblem, times: Vec<f64>, places: &[&str]) -> Dataset {
    let sol = gen_prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    let mut observations = HashMap::new();
    for &place in places {
        let series: Vec<f64> = times
            .iter()
            .map(|&t| pflow_learn::interpolate_at(&sol.t, &sol.get_variable(place), t))
            .collect();
        observations.insert(place.to_string(), series);
    }
    Dataset::new(
        times,
        observations,
        places.iter().map(|s| s.to_string()).collect(),
    )
    .unwrap()
}

#[test]
fn adjoint_matches_forward_mode_single_param() {
    let theta_true = 0.7;
    let theta = 0.5; // fit point != generating theta, so loss and gradient are nonzero
    let data = dataset_from(
        &decay_problem(theta_true),
        vec![0.25, 0.6, 1.1, 1.7],
        &["A", "B"],
    );

    let prob = decay_problem(theta);

    let sens = solve_with_sensitivities(&prob, &methods::tsit5(), &solve_opts()).unwrap();
    let (fwd_loss, fwd_grad) = mse_loss_grad(&sens, &data);

    let adj = mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    assert_close("loss", adj.loss, fwd_loss, 1e-9, 1e-6);
    // Loss the adjoint reports must also equal the plain-solve MSE (go-pflow's own
    // invariant: Loss equals MSELoss of the same trajectory).
    let plain_sol = prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    assert_close(
        "loss vs mse_loss",
        adj.loss,
        mse_loss(&plain_sol, &data),
        1e-9,
        1e-6,
    );

    assert_eq!(adj.grad.len(), fwd_grad.len());
    for (i, (&a, &f)) in adj.grad.iter().zip(fwd_grad.iter()).enumerate() {
        assert_close(&format!("grad[{i}]"), a, f, 1e-6, 1e-4);
    }
}

#[test]
fn adjoint_matches_forward_mode_two_params() {
    let data = dataset_from(
        &bimolecular_problem(0.6, 0.9),
        vec![0.1, 0.3, 0.55, 0.8],
        &["A", "B", "C", "D"],
    );

    // Fit point deliberately different from the generating parameters.
    let prob = bimolecular_problem(0.4, 1.2);

    let sens = solve_with_sensitivities(&prob, &methods::tsit5(), &solve_opts()).unwrap();
    let (fwd_loss, fwd_grad) = mse_loss_grad(&sens, &data);

    let adj = mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    assert_close("loss", adj.loss, fwd_loss, 1e-9, 1e-6);
    assert_eq!(adj.num_params, 2);
    assert_eq!(adj.param_index, sens.param_index);
    for (i, (&a, &f)) in adj.grad.iter().zip(fwd_grad.iter()).enumerate() {
        assert_close(&format!("grad[{i}]"), a, f, 1e-6, 1e-4);
    }
}

#[test]
fn adjoint_matches_forward_mode_relative_mse() {
    let theta_true = 0.7;
    let theta = 0.5;
    let data = dataset_from(
        &decay_problem(theta_true),
        vec![0.25, 0.6, 1.1, 1.7],
        &["A", "B"],
    );

    let prob = decay_problem(theta);

    let sens = solve_with_sensitivities(&prob, &methods::tsit5(), &solve_opts()).unwrap();
    let (fwd_loss, fwd_grad) = relative_mse_loss_grad(&sens, &data);

    let adj = relative_mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    assert_close("relative mse loss", adj.loss, fwd_loss, 1e-9, 1e-6);
    for (i, (&a, &f)) in adj.grad.iter().zip(fwd_grad.iter()).enumerate() {
        assert_close(&format!("grad[{i}]"), a, f, 1e-6, 1e-4);
    }
}

#[test]
fn adjoint_observation_beyond_tf_still_contributes_loss_and_gradient() {
    // A point past tf jumps at the start of the backward pass rather than being dropped.
    let theta_true = 0.7;
    let theta = 0.5;
    let data = dataset_from(&decay_problem(theta_true), vec![0.5, 1.0, 1.5, 2.5], &["A"]);

    let prob = decay_problem(theta); // tspan = [0, 2], so t=2.5 is past tf

    let sens = solve_with_sensitivities(&prob, &methods::tsit5(), &solve_opts()).unwrap();
    let (fwd_loss, fwd_grad) = mse_loss_grad(&sens, &data);

    let adj = mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    assert_close("loss", adj.loss, fwd_loss, 1e-9, 1e-6);
    for (i, (&a, &f)) in adj.grad.iter().zip(fwd_grad.iter()).enumerate() {
        assert_close(&format!("grad[{i}]"), a, f, 1e-6, 1e-4);
    }
}

#[test]
fn adjoint_rejects_zero_params() {
    let net = PetriNet::build()
        .place("A", 1.0)
        .place("B", 0.0)
        .transition("t1")
        .arc("A", "t1", 1.0)
        .arc("t1", "B", 1.0)
        .done();
    let u0: State = [("A".to_string(), 1.0), ("B".to_string(), 0.0)]
        .into_iter()
        .collect();
    let prob = LearnableProblem::new(net, u0, [0.0, 1.0]); // no rate function installed

    let mut observations = HashMap::new();
    observations.insert("A".to_string(), vec![1.0]);
    let data = Dataset::new(vec![0.5], observations, vec!["A".to_string()]).unwrap();

    match mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()) {
        Err(LearnError::ZeroParams) => {}
        Err(other) => panic!("expected LearnError::ZeroParams, got {other:?}"),
        Ok(_) => panic!("expected an error, got a solve"),
    }
}

/// Central-differences `MSELoss(plain_solve(theta))` w.r.t. the decay problem's one
/// parameter, by rebuilding the `LearnableProblem` at theta +/- h and re-solving from
/// scratch — go-pflow's `fdFullSolveGrad`, not a cross-check against another Rust
/// derivation.
fn fd_dloss_dtheta_decay(
    theta: f64,
    data: &Dataset,
    loss_fn: impl Fn(&pflow_solver::ode::Solution, &Dataset) -> f64,
) -> f64 {
    let h = 1e-6 * (1.0 + theta.abs());

    let plus = decay_problem(theta + h);
    let loss_plus = loss_fn(&plus.solve(&methods::tsit5(), &solve_opts()).unwrap(), data);

    let minus = decay_problem(theta - h);
    let loss_minus = loss_fn(
        &minus.solve(&methods::tsit5(), &solve_opts()).unwrap(),
        data,
    );

    (loss_plus - loss_minus) / (2.0 * h)
}

/// Same as `fd_dloss_dtheta_decay`, but perturbs one of the two independent parameters
/// of `bimolecular_problem` (`param == 0` perturbs theta1, `param == 1` perturbs theta2).
fn fd_dloss_dtheta_bimolecular(
    theta1: f64,
    theta2: f64,
    param: usize,
    data: &Dataset,
    loss_fn: impl Fn(&pflow_solver::ode::Solution, &Dataset) -> f64,
) -> f64 {
    let (base, h) = if param == 0 {
        (theta1, 1e-6 * (1.0 + theta1.abs()))
    } else {
        (theta2, 1e-6 * (1.0 + theta2.abs()))
    };

    let (t1p, t2p) = if param == 0 {
        (base + h, theta2)
    } else {
        (theta1, base + h)
    };
    let plus = bimolecular_problem(t1p, t2p);
    let loss_plus = loss_fn(&plus.solve(&methods::tsit5(), &solve_opts()).unwrap(), data);

    let (t1m, t2m) = if param == 0 {
        (base - h, theta2)
    } else {
        (theta1, base - h)
    };
    let minus = bimolecular_problem(t1m, t2m);
    let loss_minus = loss_fn(
        &minus.solve(&methods::tsit5(), &solve_opts()).unwrap(),
        data,
    );

    (loss_plus - loss_minus) / (2.0 * h)
}

#[test]
fn adjoint_matches_direct_fd_single_param_mse() {
    let theta_true = 0.7;
    let theta = 0.5;
    let data = dataset_from(
        &decay_problem(theta_true),
        vec![0.25, 0.6, 1.1, 1.7],
        &["A", "B"],
    );

    let prob = decay_problem(theta);
    let adj = mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    let fd_loss_grad = fd_dloss_dtheta_decay(theta, &data, mse_loss);
    assert_close(
        "adjoint grad[0] vs direct FD",
        adj.grad[0],
        fd_loss_grad,
        1e-6,
        1e-3,
    );

    // The loss itself must also match a plain re-solve at theta (not just the FD slope).
    let sol = prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    assert_close(
        "adjoint loss vs plain-solve mse_loss",
        adj.loss,
        mse_loss(&sol, &data),
        1e-9,
        1e-6,
    );
}

#[test]
fn adjoint_matches_direct_fd_single_param_relative_mse() {
    let theta_true = 0.7;
    let theta = 0.5;
    let data = dataset_from(
        &decay_problem(theta_true),
        vec![0.25, 0.6, 1.1, 1.7],
        &["A", "B"],
    );

    let prob = decay_problem(theta);
    let adj = relative_mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    let fd_loss_grad = fd_dloss_dtheta_decay(theta, &data, |sol, d| {
        pflow_learn::relative_mse_loss(sol, d)
    });
    assert_close(
        "adjoint grad[0] vs direct FD",
        adj.grad[0],
        fd_loss_grad,
        1e-6,
        1e-3,
    );
}

#[test]
fn adjoint_matches_direct_fd_two_params() {
    let data = dataset_from(
        &bimolecular_problem(0.6, 0.9),
        vec![0.1, 0.3, 0.55, 0.8],
        &["A", "B", "C", "D"],
    );

    let (theta1, theta2) = (0.4, 1.2);
    let prob = bimolecular_problem(theta1, theta2);
    let adj = mse_loss_adjoint(&prob, &data, &methods::tsit5(), &solve_opts()).unwrap();

    for param in 0..2 {
        let fd = fd_dloss_dtheta_bimolecular(theta1, theta2, param, &data, mse_loss);
        assert_close(
            &format!("adjoint grad[{param}] vs direct FD"),
            adj.grad[param],
            fd,
            1e-6,
            1e-3,
        );
    }

    let sol = prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    assert_close(
        "adjoint loss vs plain-solve mse_loss",
        adj.loss,
        mse_loss(&sol, &data),
        1e-9,
        1e-6,
    );
}
