//! Tied-parameter fitting: two transitions installed with the SAME `TiedScalar`
//! handle share one learnable rate. `LearnableProblem::num_params()` must report 1,
//! not 2, and fitting must recover the single shared rate from data generated by both
//! branches at once.

use std::collections::HashMap;

use pflow_core::net::PetriNet;
use pflow_core::State;
use pflow_learn::fit::{FitMethod, FitOptions};
use pflow_learn::{fit, mse_loss, mse_loss_grad, Dataset, LearnableProblem, TiedScalar};
use pflow_solver::methods;
use pflow_solver::ode::Options;

/// A -> t1 -> B and A -> t2 -> C, both driven by the SAME tied rate theta: A drains at
/// rate 2*theta*A (two parallel first-order channels sharing one rate constant), B and
/// C each accumulate at theta*A.
fn tied_problem(theta: f64) -> LearnableProblem {
    let net = PetriNet::build()
        .place("A", 10.0)
        .place("B", 0.0)
        .place("C", 0.0)
        .transition("t1")
        .transition("t2")
        .arc("A", "t1", 1.0)
        .arc("t1", "B", 1.0)
        .arc("A", "t2", 1.0)
        .arc("t2", "C", 1.0)
        .done();
    let u0: State = [
        ("A".to_string(), 10.0),
        ("B".to_string(), 0.0),
        ("C".to_string(), 0.0),
    ]
    .into_iter()
    .collect();
    let mut prob = LearnableProblem::new(net, u0, [0.0, 2.0]);
    let tied = TiedScalar::new(theta);
    prob.set_rate_func("t1", tied.handle());
    prob.set_rate_func("t2", tied.handle());
    prob
}

fn solve_opts() -> Options {
    Options::default_opts()
}

#[test]
fn tied_problem_reports_one_shared_parameter() {
    let prob = tied_problem(0.5);
    assert_eq!(
        prob.num_params(),
        1,
        "two tied transitions should pack to 1 param, not 2"
    );

    let (params, ranges) = prob.get_all_params();
    assert_eq!(params, vec![0.5]);
    assert_eq!(ranges["t1"], ranges["t2"]);
}

#[test]
fn tied_scalar_set_all_params_updates_both_transitions() {
    let prob = tied_problem(0.5);
    prob.set_all_params(&[1.5]);

    // Both t1 and t2 read from the same underlying handle, so a solve should show A
    // draining at combined rate 2*1.5 = 3.0 (symmetric, both branches see A directly).
    let sol = prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    let a_end = *sol.get_variable("A").last().unwrap();
    let b_end = *sol.get_variable("B").last().unwrap();
    let c_end = *sol.get_variable("C").last().unwrap();
    // B and C should be identical: both driven by the same tied rate off the same A.
    assert!(
        (b_end - c_end).abs() < 1e-9,
        "tied branches should evolve identically: B={b_end} C={c_end}"
    );
    assert!(a_end < 10.0, "A should have drained");
}

/// Synthetic dataset generated at a known shared theta, observed on all three places.
fn synthetic_dataset(theta_true: f64) -> Dataset {
    let prob = tied_problem(theta_true);
    let sol = prob.solve(&methods::tsit5(), &solve_opts()).unwrap();
    let times = vec![0.2, 0.5, 0.9, 1.3, 1.8];
    let mut observations = HashMap::new();
    for place in ["A", "B", "C"] {
        let vals: Vec<f64> = times
            .iter()
            .map(|&t| pflow_learn::interpolate_at(&sol.t, &sol.get_variable(place), t))
            .collect();
        observations.insert(place.to_string(), vals);
    }
    Dataset::new(
        times,
        observations,
        vec!["A".to_string(), "B".to_string(), "C".to_string()],
    )
    .unwrap()
}

#[test]
fn adam_recovers_shared_tied_rate() {
    const THETA_TRUE: f64 = 0.6;
    const THETA_START: f64 = 0.2;
    const THETA_TOL: f64 = 0.05;

    let data = synthetic_dataset(THETA_TRUE);
    let prob = tied_problem(THETA_START);
    assert_eq!(prob.num_params(), 1);

    let opts = FitOptions {
        max_iters: 200,
        tolerance: 1e-8,
        method: FitMethod::Adam,
        step_size: 0.05,
        verbose: false,
        solver_method: methods::tsit5(),
        solver_options: solve_opts(),
        learn_rate: 0.0,
        grad_tol: 0.0,
    };

    let result = fit(&prob, &data, &mse_loss, &mse_loss_grad, &opts).expect("fit");

    assert_eq!(result.params.len(), 1, "fit should recover exactly 1 param");
    assert!(
        result.final_loss < result.initial_loss,
        "final loss {} should be less than initial {}",
        result.final_loss,
        result.initial_loss
    );
    assert!(
        (result.params[0] - THETA_TRUE).abs() < THETA_TOL,
        "tied theta {} not within {THETA_TOL} of {THETA_TRUE}",
        result.params[0]
    );
}
