//! Discrete-stochastic simulation (Gillespie direct method), byte-exact across
//! go-pflow, pflow-rs, pflow-xyz and pflow-jl.
//!
//! The contract is the portable SSA specification shared by the four
//! implementations: a fixed PRNG ([`rng`]: SplitMix64 → xoshiro256**), a
//! ported logarithm ([`portable_log::plog`], never `f64::ln`), and a fixed
//! arithmetic order for every sum, product and comparison. Given the same
//! model, options and seed, every implementation produces the same IEEE-754
//! doubles for the ensemble mean, standard deviation and final value at every
//! grid time. The goldens in `tests/fixtures/ssa/` are generated by go-pflow
//! and copied here byte-identical; they are never regenerated to make a test
//! pass.
//!
//! `pflow_core::PetriNet` keeps places and transitions in `HashMap`s and its
//! arcs carry neither a read type nor a kinetic flag, so the SSA takes its own
//! **ordered** model ([`SsaModel`]): declaration order is the order — no
//! sorting, no map iteration anywhere on the numeric path.

pub mod portable_log;
pub mod rng;
pub mod sde;

pub use portable_log::plog;
pub use rng::{splitmix64, Xoshiro256};
pub use sde::{
    combinations_real, simulate_sde, simulate_sde_compiled, SdeOptions, SdeResult,
    CHEMICAL_LANGEVIN_ASSUMPTION,
};

use std::collections::HashMap;
use std::fmt;

/// Upper bound on SSA steps per realization (spec §3.4).
pub const MAX_STEPS: usize = 1_000_000;

/// A place: `capacity == 0` means unbounded.
#[derive(Debug, Clone, PartialEq)]
pub struct SsaPlace {
    pub id: String,
    pub initial: i64,
    pub capacity: i64,
}

/// A transition: `rate == 0.0` means the default rate `1.0`.
///
/// `delay > 0.0` makes it a timed transition (spec §5): it has no rate, starts
/// the instant it is enabled — consuming its inputs then — and produces its
/// outputs exactly `delay` later, one clock per enabling. It must consume
/// something, or it would restart forever in zero time; `compile` refuses.
#[derive(Debug, Clone, PartialEq)]
pub struct SsaTransition {
    pub id: String,
    pub rate: f64,
    pub delay: f64,
}

/// Arc semantics. `Read` and `Inhibitor` arcs are always place → transition.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArcKind {
    Flow,
    Inhibitor,
    Read,
}

/// An arc: `weight == 0` means the default weight `1`. `kinetic` only matters
/// on a flow arc into a transition (an input); a non-kinetic input gates and
/// is consumed but does not enter the propensity product.
#[derive(Debug, Clone, PartialEq)]
pub struct SsaArc {
    pub from: String,
    pub to: String,
    pub weight: i64,
    pub kind: ArcKind,
    pub kinetic: bool,
}

impl SsaArc {
    /// An ordinary kinetic flow arc with weight 1.
    pub fn flow(from: impl Into<String>, to: impl Into<String>) -> Self {
        Self::flow_weighted(from, to, 1)
    }

    /// An ordinary kinetic flow arc with the given weight.
    pub fn flow_weighted(from: impl Into<String>, to: impl Into<String>, weight: i64) -> Self {
        Self {
            from: from.into(),
            to: to.into(),
            weight,
            kind: ArcKind::Flow,
            kinetic: true,
        }
    }
}

/// Three ordered lists. Order is normative.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SsaModel {
    pub places: Vec<SsaPlace>,
    pub transitions: Vec<SsaTransition>,
    pub arcs: Vec<SsaArc>,
}

/// Simulation options. `seed == 0` is treated as `1` (spec §3.6).
#[derive(Debug, Clone, PartialEq)]
pub struct SsaOptions {
    pub horizon: f64,
    pub samples: usize,
    pub realizations: usize,
    pub seed: u64,
}

impl Default for SsaOptions {
    fn default() -> Self {
        Self {
            horizon: 10.0,
            samples: 101,
            realizations: 1,
            seed: 1,
        }
    }
}

/// Ensemble result. `values[p][i]` is the mean over realizations of place `p`
/// at `times[i]`; `stddev` is present only when `realizations > 1`;
/// `final_[p] == values[p][samples-1]` bit for bit.
#[derive(Debug, Clone, PartialEq)]
pub struct SsaResult {
    pub places: Vec<String>,
    pub times: Vec<f64>,
    pub values: Vec<Vec<f64>>,
    pub stddev: Option<Vec<Vec<f64>>>,
    pub final_: Vec<f64>,
}

impl SsaResult {
    /// Index of a place by id.
    pub fn place_index(&self, id: &str) -> Option<usize> {
        self.places.iter().position(|p| p == id)
    }
}

/// Model or option errors detected before any random draw.
#[derive(Debug, Clone, PartialEq)]
pub enum SsaError {
    DuplicateId(String),
    UnknownEndpoint { arc: usize, id: String },
    ArcBetweenSameKind { arc: usize },
    ReadOrInhibitorFromTransition { arc: usize },
    NegativeInitial(String),
    NegativeCapacity(String),
    NegativeWeight { arc: usize },
    NegativeRate(String),
    NegativeDelay(String),
    DelayWithoutInput(String),
    BadOptions(String),
}

impl fmt::Display for SsaError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SsaError::DuplicateId(id) => write!(f, "duplicate id {id:?}"),
            SsaError::UnknownEndpoint { arc, id } => {
                write!(
                    f,
                    "arc {arc}: endpoint {id:?} is neither a place nor a transition"
                )
            }
            SsaError::ArcBetweenSameKind { arc } => {
                write!(f, "arc {arc}: must connect a place and a transition")
            }
            SsaError::ReadOrInhibitorFromTransition { arc } => {
                write!(
                    f,
                    "arc {arc}: read/inhibitor arcs must be written place -> transition"
                )
            }
            SsaError::NegativeInitial(id) => write!(f, "place {id:?}: negative initial marking"),
            SsaError::NegativeCapacity(id) => write!(f, "place {id:?}: negative capacity"),
            SsaError::NegativeWeight { arc } => write!(f, "arc {arc}: negative weight"),
            SsaError::NegativeRate(id) => write!(f, "transition {id:?}: negative rate"),
            SsaError::NegativeDelay(id) => write!(f, "transition {id:?}: negative delay"),
            SsaError::DelayWithoutInput(id) => write!(
                f,
                "transition {id:?}: a delay on a transition with no consuming input would restart forever in zero time"
            ),
            SsaError::BadOptions(msg) => write!(f, "bad options: {msg}"),
        }
    }
}

impl std::error::Error for SsaError {}

/// `C(m, w)` computed exactly as go-pflow does: multiply then divide, once per
/// factor, in that order. Never a precomputed factorial ratio.
pub fn combinations(m: i64, w: i64) -> f64 {
    if w <= 0 {
        return 1.0;
    }
    if m < w {
        return 0.0;
    }
    let mut result = 1.0;
    for i in 0..w {
        result *= (m - i) as f64;
        result /= (i + 1) as f64;
    }
    result
}

/// Compiled transition: every list is in `arcs[]` order except `caps`, which
/// is in place order.
#[derive(Debug, Clone)]
struct Compiled {
    rate: f64,
    /// > 0: a timed transition (spec §5); `rate` is then 0.
    delay: f64,
    /// (place index, weight, kinetic)
    inputs: Vec<(usize, i64, bool)>,
    /// (place index, weight)
    outputs: Vec<(usize, i64)>,
    reads: Vec<(usize, i64)>,
    inhibits: Vec<(usize, i64)>,
    /// (place index, net delta, capacity)
    caps: Vec<(usize, i64, i64)>,
}

impl Compiled {
    /// §5: every constraint lets a delayed transition start — consuming
    /// inputs present and the non-consuming gates open. The exponential path
    /// folds the input test into the propensity; a timed transition has none
    /// and asks here.
    fn enabled(&self, marking: &[i64]) -> bool {
        for &(p, w, _) in &self.inputs {
            if marking[p] < w {
                return false;
            }
        }
        self.gated(marking)
    }

    fn gated(&self, marking: &[i64]) -> bool {
        for &(p, w) in &self.reads {
            if marking[p] < w {
                return false;
            }
        }
        for &(p, w) in &self.inhibits {
            if marking[p] >= w {
                return false;
            }
        }
        for &(p, d, limit) in &self.caps {
            if marking[p] + d > limit {
                return false;
            }
        }
        true
    }
}

/// The compiled form of an [`SsaModel`]: validated once, then reused across
/// realizations.
#[derive(Debug, Clone)]
pub struct CompiledModel {
    place_ids: Vec<String>,
    initial: Vec<i64>,
    transitions: Vec<Compiled>,
}

impl CompiledModel {
    /// Place ids in place order.
    pub fn place_ids(&self) -> &[String] {
        &self.place_ids
    }

    /// Initial marking in place order.
    pub fn initial_marking(&self) -> &[i64] {
        &self.initial
    }

    /// Propensity of every transition (transition order) and their total,
    /// summed strictly left to right (spec §3.3).
    pub fn propensities(&self, marking: &[i64], out: &mut Vec<f64>) -> f64 {
        out.clear();
        let mut a0 = 0.0;
        for t in &self.transitions {
            let mut a = t.rate;
            for &(p, w, kinetic) in &t.inputs {
                let m = marking[p];
                if m < w {
                    a = 0.0;
                    break;
                }
                if kinetic {
                    a *= combinations(m, w);
                }
            }
            if a > 0.0 && !t.gated(marking) {
                a = 0.0;
            }
            out.push(a);
            a0 += a;
        }
        a0
    }
}

/// Validate and compile a model (spec §3.1).
pub fn compile(model: &SsaModel) -> Result<CompiledModel, SsaError> {
    let mut place_index: HashMap<&str, usize> = HashMap::new();
    let mut trans_index: HashMap<&str, usize> = HashMap::new();
    for (i, p) in model.places.iter().enumerate() {
        if place_index.insert(p.id.as_str(), i).is_some() {
            return Err(SsaError::DuplicateId(p.id.clone()));
        }
        if p.initial < 0 {
            return Err(SsaError::NegativeInitial(p.id.clone()));
        }
        if p.capacity < 0 {
            return Err(SsaError::NegativeCapacity(p.id.clone()));
        }
    }
    for (j, t) in model.transitions.iter().enumerate() {
        if place_index.contains_key(t.id.as_str()) || trans_index.insert(t.id.as_str(), j).is_some()
        {
            return Err(SsaError::DuplicateId(t.id.clone()));
        }
        if t.rate < 0.0 {
            return Err(SsaError::NegativeRate(t.id.clone()));
        }
        if t.delay < 0.0 {
            return Err(SsaError::NegativeDelay(t.id.clone()));
        }
    }

    let mut compiled: Vec<Compiled> = model
        .transitions
        .iter()
        .map(|t| Compiled {
            // A timer, not a race: a delayed transition has no propensity.
            rate: if t.delay > 0.0 {
                0.0
            } else if t.rate == 0.0 {
                1.0
            } else {
                t.rate
            },
            delay: t.delay,
            inputs: Vec::new(),
            outputs: Vec::new(),
            reads: Vec::new(),
            inhibits: Vec::new(),
            caps: Vec::new(),
        })
        .collect();

    for (k, arc) in model.arcs.iter().enumerate() {
        if arc.weight < 0 {
            return Err(SsaError::NegativeWeight { arc: k });
        }
        let w = if arc.weight == 0 { 1 } else { arc.weight };
        let from_place = place_index.get(arc.from.as_str()).copied();
        let from_trans = trans_index.get(arc.from.as_str()).copied();
        let to_place = place_index.get(arc.to.as_str()).copied();
        let to_trans = trans_index.get(arc.to.as_str()).copied();
        if from_place.is_none() && from_trans.is_none() {
            return Err(SsaError::UnknownEndpoint {
                arc: k,
                id: arc.from.clone(),
            });
        }
        if to_place.is_none() && to_trans.is_none() {
            return Err(SsaError::UnknownEndpoint {
                arc: k,
                id: arc.to.clone(),
            });
        }
        match (from_place, to_trans, from_trans, to_place) {
            (Some(p), Some(t), _, _) => match arc.kind {
                ArcKind::Flow => compiled[t].inputs.push((p, w, arc.kinetic)),
                ArcKind::Read => compiled[t].reads.push((p, w)),
                ArcKind::Inhibitor => compiled[t].inhibits.push((p, w)),
            },
            (_, _, Some(t), Some(p)) => match arc.kind {
                ArcKind::Flow => compiled[t].outputs.push((p, w)),
                ArcKind::Read | ArcKind::Inhibitor => {
                    return Err(SsaError::ReadOrInhibitorFromTransition { arc: k })
                }
            },
            _ => return Err(SsaError::ArcBetweenSameKind { arc: k }),
        }
    }

    for (t, c) in model.transitions.iter().zip(compiled.iter()) {
        if c.delay > 0.0 && c.inputs.is_empty() {
            return Err(SsaError::DelayWithoutInput(t.id.clone()));
        }
    }

    // Capacity bounds: net delta per place, in place order.
    for t in compiled.iter_mut() {
        let mut delta: HashMap<usize, i64> = HashMap::new();
        for &(p, w) in &t.outputs {
            *delta.entry(p).or_insert(0) += w;
        }
        for &(p, w, _) in &t.inputs {
            *delta.entry(p).or_insert(0) -= w;
        }
        for (p, place) in model.places.iter().enumerate() {
            if place.capacity > 0 {
                if let Some(&d) = delta.get(&p) {
                    if d > 0 {
                        t.caps.push((p, d, place.capacity));
                    }
                }
            }
        }
    }

    Ok(CompiledModel {
        place_ids: model.places.iter().map(|p| p.id.clone()).collect(),
        initial: model.places.iter().map(|p| p.initial).collect(),
        transitions: compiled,
    })
}

/// The sample grid: `times[i] = i * (horizon / (samples - 1))` (spec §3.5).
pub fn sample_grid(horizon: f64, samples: usize) -> Vec<f64> {
    let step = horizon / (samples - 1) as f64;
    (0..samples).map(|i| i as f64 * step).collect()
}

/// One realization (spec §3.4): returns `traj[p][i]` for the given grid.
pub fn realization(model: &CompiledModel, times: &[f64], rng: &mut Xoshiro256) -> Vec<Vec<f64>> {
    let n_places = model.place_ids.len();
    let n_trans = model.transitions.len();
    let samples = times.len();
    let mut marking: Vec<i64> = model.initial.clone();
    let mut traj: Vec<Vec<f64>> = vec![Vec::with_capacity(samples); n_places];
    let mut propensity: Vec<f64> = Vec::with_capacity(n_trans);

    let mut t = 0.0_f64;
    let mut next = 0usize;

    fn record(times: &[f64], t: f64, next: &mut usize, marking: &[i64], traj: &mut [Vec<f64>]) {
        while *next < times.len() && times[*next] <= t {
            for (p, m) in marking.iter().enumerate() {
                traj[p].push(*m as f64);
            }
            *next += 1;
        }
    }

    record(times, t, &mut next, &marking, &mut traj);
    let t_end = times[samples - 1];
    // §5: delayed firings in progress as (completion time, transition),
    // sorted by time, FIFO among ties. Delay-free nets never touch it, so
    // their sample paths are exactly what they were.
    let mut queue: Vec<(f64, usize)> = Vec::new();
    let timed = model.transitions.iter().any(|c| c.delay > 0.0);
    let mut step = 0usize;
    while step < MAX_STEPS && t < t_end {
        step += 1;
        // 0. start every enabled delayed transition at this instant, in
        //    declaration order, one start per pass, passes until none starts.
        if timed {
            let mut again = true;
            while again {
                again = false;
                for j in 0..n_trans {
                    let c = &model.transitions[j];
                    if c.delay > 0.0 && c.enabled(&marking) {
                        for &(p, w, _) in &c.inputs {
                            marking[p] -= w;
                        }
                        let at = t + c.delay;
                        let mut i = 0usize;
                        while i < queue.len() && queue[i].0 <= at {
                            i += 1;
                        }
                        queue.insert(i, (at, j));
                        again = true;
                    }
                }
            }
        }
        let a0 = model.propensities(&marking, &mut propensity);
        if a0 <= 0.0 && queue.is_empty() {
            break;
        }
        // No draw when nothing can race; the clock alone moves time.
        let mut dt = f64::INFINITY;
        if a0 > 0.0 {
            let x1 = rng.uniform();
            let u = 1.0 - x1;
            dt = (-plog(u)) / a0;
        }
        // A completion due before the draw pre-empts it. The draw is
        // discarded, not deferred: the race is memoryless.
        if let Some(&(at, j)) = queue.first() {
            if at <= t + dt {
                t = at; // assigned, not accumulated: same double as Go
                record(times, t, &mut next, &marking, &mut traj);
                if t > t_end {
                    break;
                }
                queue.remove(0);
                for &(p, w) in &model.transitions[j].outputs {
                    marking[p] += w;
                }
                continue;
            }
        }
        t += dt;
        record(times, t, &mut next, &marking, &mut traj);
        if t > t_end {
            break;
        }
        let x2 = rng.uniform();
        let r = x2 * a0;
        let mut chosen = n_trans - 1;
        let mut acc = 0.0_f64;
        for (j, a) in propensity.iter().enumerate() {
            acc += *a;
            if r <= acc {
                chosen = j;
                break;
            }
        }
        let tr = &model.transitions[chosen];
        for &(p, w, _) in &tr.inputs {
            marking[p] -= w;
        }
        for &(p, w) in &tr.outputs {
            marking[p] += w;
        }
    }
    while next < samples {
        for (p, m) in marking.iter().enumerate() {
            traj[p].push(*m as f64);
        }
        next += 1;
    }
    traj
}

/// Run the ensemble (spec §3.6–3.7).
pub fn simulate(model: &SsaModel, opts: &SsaOptions) -> Result<SsaResult, SsaError> {
    let compiled = compile(model)?;
    simulate_compiled(&compiled, opts)
}

/// Run the ensemble on an already-compiled model.
pub fn simulate_compiled(model: &CompiledModel, opts: &SsaOptions) -> Result<SsaResult, SsaError> {
    if opts.samples < 2 {
        return Err(SsaError::BadOptions("samples must be >= 2".into()));
    }
    if opts.realizations < 1 {
        return Err(SsaError::BadOptions("realizations must be >= 1".into()));
    }
    if !opts.horizon.is_finite() || opts.horizon <= 0.0 {
        return Err(SsaError::BadOptions(
            "horizon must be positive and finite".into(),
        ));
    }

    let n_places = model.place_ids.len();
    let samples = opts.samples;
    let times = sample_grid(opts.horizon, samples);

    let base = if opts.seed == 0 { 1 } else { opts.seed };
    let mut sums: Vec<Vec<f64>> = vec![vec![0.0; samples]; n_places];
    let mut sumsq: Vec<Vec<f64>> = vec![vec![0.0; samples]; n_places];

    for r in 0..opts.realizations {
        let mut rng = Xoshiro256::new(base.wrapping_add(r as u64));
        let traj = realization(model, &times, &mut rng);
        for p in 0..n_places {
            for i in 0..samples {
                let v = traj[p][i];
                sums[p][i] += v;
                sumsq[p][i] += v * v;
            }
        }
    }

    let n = opts.realizations as f64;
    let mut values: Vec<Vec<f64>> = vec![vec![0.0; samples]; n_places];
    let mut stddev: Option<Vec<Vec<f64>>> = if opts.realizations > 1 {
        Some(vec![vec![0.0; samples]; n_places])
    } else {
        None
    };
    for p in 0..n_places {
        for i in 0..samples {
            let mean = sums[p][i] / n;
            values[p][i] = mean;
            if let Some(sd) = stddev.as_mut() {
                let mut variance = (sumsq[p][i] / n) - (mean * mean);
                if variance < 0.0 {
                    variance = 0.0;
                }
                sd[p][i] = variance.sqrt();
            }
        }
    }
    let final_: Vec<f64> = values.iter().map(|v| v[samples - 1]).collect();

    Ok(SsaResult {
        places: model.place_ids.clone(),
        times,
        values,
        stddev,
        final_,
    })
}

impl SsaModel {
    /// Build an ordered SSA model from a `pflow_core::PetriNet`.
    ///
    /// `PetriNet` keeps places and transitions in `HashMap`s, so the caller
    /// must supply the place and transition order explicitly. Arc weights are
    /// `weight_sum()` and must be integral; `inhibit_transition` on an input
    /// arc becomes an [`ArcKind::Inhibitor`]; every input is kinetic. Places
    /// take `token_count()` (must be integral and non-negative) as the initial
    /// marking and the first capacity component as `capacity`. Rates default
    /// to 1.0 when absent from `rates`.
    pub fn from_petri_net(
        net: &pflow_core::PetriNet,
        place_order: &[String],
        transition_order: &[String],
        rates: &HashMap<String, f64>,
    ) -> Result<Self, String> {
        let mut places = Vec::with_capacity(place_order.len());
        for id in place_order {
            let p = net
                .places
                .get(id)
                .ok_or_else(|| format!("place {id:?} not in net"))?;
            let initial = integral(p.token_count()).ok_or_else(|| {
                format!(
                    "place {id:?}: initial marking {} is not integral",
                    p.token_count()
                )
            })?;
            let cap = p.capacity.first().copied().unwrap_or(0.0);
            let capacity = integral(cap)
                .ok_or_else(|| format!("place {id:?}: capacity {cap} is not integral"))?;
            places.push(SsaPlace {
                id: id.clone(),
                initial,
                capacity,
            });
        }
        let mut transitions = Vec::with_capacity(transition_order.len());
        for id in transition_order {
            if !net.transitions.contains_key(id) {
                return Err(format!("transition {id:?} not in net"));
            }
            transitions.push(SsaTransition {
                id: id.clone(),
                rate: rates.get(id).copied().unwrap_or(1.0),
                delay: 0.0,
            });
        }
        let mut arcs = Vec::with_capacity(net.arcs.len());
        for (k, a) in net.arcs.iter().enumerate() {
            let ws = a.weight_sum();
            let weight =
                integral(ws).ok_or_else(|| format!("arc {k}: weight {ws} is not integral"))?;
            let kind = if a.inhibit_transition {
                ArcKind::Inhibitor
            } else {
                ArcKind::Flow
            };
            arcs.push(SsaArc {
                from: a.source.clone(),
                to: a.target.clone(),
                weight,
                kind,
                kinetic: true,
            });
        }
        Ok(SsaModel {
            places,
            transitions,
            arcs,
        })
    }
}

fn integral(x: f64) -> Option<i64> {
    if x.is_finite() && x.fract() == 0.0 && x >= 0.0 && x <= i64::MAX as f64 {
        Some(x as i64)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn chain() -> SsaModel {
        SsaModel {
            places: vec![
                SsaPlace {
                    id: "a".into(),
                    initial: 100,
                    capacity: 0,
                },
                SsaPlace {
                    id: "b".into(),
                    initial: 0,
                    capacity: 0,
                },
                SsaPlace {
                    id: "c".into(),
                    initial: 0,
                    capacity: 0,
                },
            ],
            transitions: vec![
                SsaTransition {
                    id: "ab".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "bc".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
            ],
            arcs: vec![
                SsaArc::flow("a", "ab"),
                SsaArc::flow("ab", "b"),
                SsaArc::flow("b", "bc"),
                SsaArc::flow("bc", "c"),
            ],
        }
    }

    fn sir() -> SsaModel {
        SsaModel {
            places: vec![
                SsaPlace {
                    id: "S".into(),
                    initial: 990,
                    capacity: 0,
                },
                SsaPlace {
                    id: "I".into(),
                    initial: 10,
                    capacity: 0,
                },
                SsaPlace {
                    id: "R".into(),
                    initial: 0,
                    capacity: 0,
                },
            ],
            transitions: vec![
                SsaTransition {
                    id: "infect".into(),
                    rate: 0.0005,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "recover".into(),
                    rate: 0.1,
                    delay: 0.0,
                },
            ],
            arcs: vec![
                SsaArc::flow("S", "infect"),
                SsaArc::flow("I", "infect"),
                SsaArc::flow_weighted("infect", "I", 2),
                SsaArc::flow("I", "recover"),
                SsaArc::flow("recover", "R"),
            ],
        }
    }

    fn dimer() -> SsaModel {
        SsaModel {
            places: vec![
                SsaPlace {
                    id: "A".into(),
                    initial: 50,
                    capacity: 0,
                },
                SsaPlace {
                    id: "B".into(),
                    initial: 0,
                    capacity: 0,
                },
            ],
            transitions: vec![
                SsaTransition {
                    id: "dimerise".into(),
                    rate: 0.01,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "dissociate".into(),
                    rate: 0.1,
                    delay: 0.0,
                },
            ],
            arcs: vec![
                SsaArc::flow_weighted("A", "dimerise", 2),
                SsaArc::flow("dimerise", "B"),
                SsaArc::flow("B", "dissociate"),
                SsaArc::flow_weighted("dissociate", "A", 2),
            ],
        }
    }

    #[test]
    fn combinations_matches_go() {
        assert_eq!(combinations(5, 0), 1.0);
        assert_eq!(combinations(1, 2), 0.0);
        assert_eq!(combinations(50, 2), 1225.0);
        assert_eq!(combinations(48, 2), 1128.0);
        assert_eq!(combinations(7, 3), 35.0);
        // Spec §3.2: the multiply-then-divide order gives exactly this double.
        assert_eq!(combinations(1000, 20), 3.3948281130245768e+41);
    }

    #[test]
    fn sample_grid_is_i_times_step() {
        let g = sample_grid(8.0, 60);
        assert_eq!(g.len(), 60);
        assert_eq!(g[0], 0.0);
        let step = 8.0 / 59.0;
        assert_eq!(g[59], 59.0 * step);
        assert_eq!(g[17], 17.0 * step);
    }

    #[test]
    fn chain_reference_trace_spec_3_8() {
        // First step of realization 0 (seed 42) reproduces the spec's trace.
        let compiled = compile(&chain()).unwrap();
        let mut props = Vec::new();
        let marking = compiled.initial_marking().to_vec();
        let a0 = compiled.propensities(&marking, &mut props);
        assert_eq!(a0, 100.0);
        let mut g = Xoshiro256::new(42);
        let x1 = g.uniform();
        let u = 1.0 - x1;
        assert_eq!(u.to_bits(), 0x3FED_50FE_9A3E_7A28);
        let dt = (-plog(u)) / a0;
        assert_eq!(dt.to_bits(), 0x3F4C_B386_8D3A_58D8);
        let x2 = g.uniform();
        assert_eq!(x2 * a0, 37.89802506626686);
        // step 2 dt
        let x1 = g.uniform();
        let u = 1.0 - x1;
        assert_eq!(u, 0.31995658897186063);
        assert_eq!(((-plog(u)) / a0).to_bits(), 0x3F87_56A0_E5FA_32AF);
    }

    #[test]
    fn chain_ensemble_spec_3_8() {
        let res = simulate(
            &chain(),
            &SsaOptions {
                horizon: 10.0,
                samples: 11,
                realizations: 3,
                seed: 42,
            },
        )
        .unwrap();
        let a = res.place_index("a").unwrap();
        assert_eq!(res.values[a][1].to_bits(), 0x4041_D555_5555_5555);
        assert_eq!(
            res.stddev.as_ref().unwrap()[a][1].to_bits(),
            0x400A_660E_223F_1B70
        );
        assert_eq!(res.final_, vec![0.0, 0.0, 100.0]);
        for p in 0..3 {
            assert_eq!(res.final_[p].to_bits(), res.values[p][10].to_bits());
        }
    }

    #[test]
    fn sir_reference_spec_3_8() {
        let compiled = compile(&sir()).unwrap();
        let mut props = Vec::new();
        let a0 = compiled.propensities(&[990, 10, 0], &mut props);
        assert_eq!(a0.to_bits(), 0x4017_CCCC_CCCC_CCCD);
        let mut g = Xoshiro256::new(11);
        let x1 = g.uniform();
        assert_eq!(x1, 0.223274216617233);
        let dt = (-plog(1.0 - x1)) / a0;
        assert_eq!(dt.to_bits(), 0x3FA5_BDFF_7C4D_22D7);
        assert_eq!(g.uniform() * a0, 0.5190446803802753);
        // After infect: S 989, I 11.
        let a0 = compiled.propensities(&[989, 11, 0], &mut props);
        assert_eq!(a0.to_bits(), 0x401A_2872_B020_C49C);

        let res = simulate(
            &sir(),
            &SsaOptions {
                horizon: 40.0,
                samples: 81,
                realizations: 8,
                seed: 11,
            },
        )
        .unwrap();
        assert_eq!(
            res.stddev.as_ref().unwrap()[0][1].to_bits(),
            0x3FF5_2A7F_A9D2_F8EA
        );
        assert_eq!(res.final_, vec![9.625, 71.5, 918.875]);
    }

    #[test]
    fn dimer_reference_spec_3_8() {
        let compiled = compile(&dimer()).unwrap();
        let mut props = Vec::new();
        assert_eq!(compiled.propensities(&[50, 0], &mut props), 12.25);
        let mut g = Xoshiro256::new(7);
        let dt = (-plog(1.0 - g.uniform())) / 12.25;
        assert_eq!(dt.to_bits(), 0x3FB9_3365_B785_5C40);
        assert_eq!(
            compiled.propensities(&[48, 1], &mut props).to_bits(),
            0x4026_C28F_5C28_F5C2
        );
        let res = simulate(
            &dimer(),
            &SsaOptions {
                horizon: 5.0,
                samples: 21,
                realizations: 4,
                seed: 7,
            },
        )
        .unwrap();
        assert_eq!(
            res.stddev.as_ref().unwrap()[0][1].to_bits(),
            0x3FFA_8872_93FD_6F34
        );
        assert_eq!(res.final_, vec![23.5, 13.25]);
    }

    #[test]
    fn seed_zero_is_seed_one() {
        let m = chain();
        let o = SsaOptions {
            horizon: 10.0,
            samples: 11,
            realizations: 2,
            seed: 0,
        };
        let a = simulate(&m, &o).unwrap();
        let b = simulate(&m, &SsaOptions { seed: 1, ..o }).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn single_realization_has_no_stddev() {
        let res = simulate(
            &chain(),
            &SsaOptions {
                horizon: 1.0,
                samples: 3,
                realizations: 1,
                seed: 3,
            },
        )
        .unwrap();
        assert!(res.stddev.is_none());
        assert_eq!(res.times.len(), 3);
    }

    #[test]
    fn gating_semantics() {
        // Capacity: fill is blocked when p + 1 > 2. Inhibitor: blocked while g >= 1.
        // Read: drain requires g >= 1 but does not consume it.
        let model = SsaModel {
            places: vec![
                SsaPlace {
                    id: "p".into(),
                    initial: 2,
                    capacity: 2,
                },
                SsaPlace {
                    id: "g".into(),
                    initial: 1,
                    capacity: 0,
                },
                SsaPlace {
                    id: "q".into(),
                    initial: 0,
                    capacity: 0,
                },
            ],
            transitions: vec![
                SsaTransition {
                    id: "fill".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "blocked".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "drain".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
                SsaTransition {
                    id: "nonkin".into(),
                    rate: 1.0,
                    delay: 0.0,
                },
            ],
            arcs: vec![
                SsaArc::flow("fill", "p"),
                SsaArc {
                    from: "g".into(),
                    to: "blocked".into(),
                    weight: 1,
                    kind: ArcKind::Inhibitor,
                    kinetic: true,
                },
                SsaArc::flow("blocked", "q"),
                SsaArc {
                    from: "g".into(),
                    to: "drain".into(),
                    weight: 1,
                    kind: ArcKind::Read,
                    kinetic: true,
                },
                SsaArc::flow("p", "drain"),
                SsaArc::flow("drain", "q"),
                SsaArc {
                    from: "p".into(),
                    to: "nonkin".into(),
                    weight: 2,
                    kind: ArcKind::Flow,
                    kinetic: false,
                },
            ],
        };
        let compiled = compile(&model).unwrap();
        let mut props = Vec::new();
        let a0 = compiled.propensities(&[2, 1, 0], &mut props);
        // fill blocked by capacity, blocked inhibited, drain = 1*C(2,1) = 2, nonkin = 1 (no product).
        assert_eq!(props, vec![0.0, 0.0, 2.0, 1.0]);
        assert_eq!(a0, 3.0);
        let a0 = compiled.propensities(&[1, 0, 0], &mut props);
        // fill admitted (1+1 <= 2), blocked admitted (g < 1), drain gated by read, nonkin m<w.
        assert_eq!(props, vec![1.0, 1.0, 0.0, 0.0]);
        assert_eq!(a0, 2.0);
    }

    #[test]
    fn compile_rejects_bad_models() {
        let mut m = chain();
        m.arcs.push(SsaArc::flow("a", "zzz"));
        assert!(matches!(
            compile(&m),
            Err(SsaError::UnknownEndpoint { arc: 4, .. })
        ));
        let mut m = chain();
        m.arcs.push(SsaArc {
            from: "ab".into(),
            to: "b".into(),
            weight: 1,
            kind: ArcKind::Read,
            kinetic: true,
        });
        assert!(matches!(
            compile(&m),
            Err(SsaError::ReadOrInhibitorFromTransition { arc: 4 })
        ));
        let mut m = chain();
        m.arcs.push(SsaArc::flow("a", "b"));
        assert!(matches!(
            compile(&m),
            Err(SsaError::ArcBetweenSameKind { arc: 4 })
        ));
        let mut m = chain();
        m.places[1].id = "a".into();
        assert!(matches!(compile(&m), Err(SsaError::DuplicateId(_))));
        assert!(matches!(
            simulate(
                &chain(),
                &SsaOptions {
                    samples: 1,
                    ..SsaOptions::default()
                }
            ),
            Err(SsaError::BadOptions(_))
        ));
    }

    #[test]
    fn from_petri_net_roundtrip() {
        let mut net = pflow_core::PetriNet::new();
        net.add_place("a", vec![100.0], vec![], 0.0, 0.0, None);
        net.add_place("b", vec![0.0], vec![], 0.0, 0.0, None);
        net.add_place("c", vec![0.0], vec![], 0.0, 0.0, None);
        net.add_transition("ab", "", 0.0, 0.0, None);
        net.add_transition("bc", "", 0.0, 0.0, None);
        net.add_arc("a", "ab", vec![1.0], false);
        net.add_arc("ab", "b", vec![1.0], false);
        net.add_arc("b", "bc", vec![1.0], false);
        net.add_arc("bc", "c", vec![1.0], false);
        let order_p: Vec<String> = ["a", "b", "c"].iter().map(|s| s.to_string()).collect();
        let order_t: Vec<String> = ["ab", "bc"].iter().map(|s| s.to_string()).collect();
        let rates: HashMap<String, f64> = [("ab".to_string(), 1.0), ("bc".to_string(), 1.0)]
            .into_iter()
            .collect();
        let m = SsaModel::from_petri_net(&net, &order_p, &order_t, &rates).unwrap();
        assert_eq!(m, chain());
        let o = SsaOptions {
            horizon: 10.0,
            samples: 11,
            realizations: 3,
            seed: 42,
        };
        assert_eq!(simulate(&m, &o).unwrap(), simulate(&chain(), &o).unwrap());
    }
}
